package methodjit

var opBackendPolicies = [...]OpBackendPolicy{
	OpConstInt:                      OpBackendPreservesTableArrayBounds,
	OpConstFloat:                    OpBackendPreservesTableArrayBounds,
	OpConstBool:                     OpBackendPreservesTableArrayBounds,
	OpConstNil:                      OpBackendPreservesTableArrayBounds,
	OpConstString:                   OpBackendPreservesTableArrayBounds,
	OpLoadSlot:                      OpBackendPreservesTableArrayBounds,
	OpStoreSlot:                     OpBackendPreservesTableArrayBounds,
	OpAdd:                           OpBackendPreservesTableArrayBounds,
	OpSub:                           OpBackendPreservesTableArrayBounds,
	OpMul:                           OpBackendPreservesTableArrayBounds,
	OpDiv:                           OpBackendPreservesTableArrayBounds,
	OpMod:                           OpBackendPreservesTableArrayBounds,
	OpUnm:                           OpBackendPreservesTableArrayBounds,
	OpNot:                           OpBackendPreservesTableArrayBounds,
	OpLen:                           OpBackendClearsTableArrayBounds,
	OpAddInt:                        OpBackendPreservesTableArrayBounds,
	OpSubInt:                        OpBackendPreservesTableArrayBounds,
	OpMulInt:                        OpBackendPreservesTableArrayBounds,
	OpModInt:                        OpBackendPreservesTableArrayBounds,
	OpNegInt:                        OpBackendPreservesTableArrayBounds,
	OpAddFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpSubFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpMulFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpDivFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpNegFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpSqrt:                          OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpFloor:                         OpBackendPreservesTableArrayBounds,
	OpFMA:                           OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpFMSUB:                         OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpComplexEscapeInSet:            OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpComplexEscapeRowCount:         OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpRecordArrayLoopSpecialization: OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpEq:                            OpBackendPreservesTableArrayBounds,
	OpLt:                            OpBackendPreservesTableArrayBounds,
	OpLe:                            OpBackendPreservesTableArrayBounds,
	OpEqInt:                         OpBackendPreservesTableArrayBounds,
	OpLtInt:                         OpBackendPreservesTableArrayBounds,
	OpLeInt:                         OpBackendPreservesTableArrayBounds,
	OpModZeroInt:                    OpBackendPreservesTableArrayBounds,
	OpLtFloat:                       OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache | OpBackendPreservesScratchFPRCache,
	OpLeFloat:                       OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache | OpBackendPreservesScratchFPRCache,
	OpEqString:                      OpBackendPreservesTableArrayBounds,
	OpStringFormatConstLen:          OpBackendPreservesTableArrayBounds | OpBackendClearsTableArrayBounds,
	OpNewTable:                      0,
	OpSetTable:                      OpBackendClearsTableArrayBounds | OpBackendInvalidatesShape,
	OpTableArrayHeader:              OpBackendPreservesTableArrayBounds,
	OpTableArrayLen:                 OpBackendPreservesTableArrayBounds,
	OpTableArrayData:                OpBackendPreservesTableArrayBounds,
	OpTableArrayLoad:                OpBackendPreservesTableArrayBounds,
	OpTableShapeID:                  OpBackendPreservesTableArrayBounds,
	OpTableArrayStore:               OpBackendPreservesTableArrayBounds,
	OpTableArraySwap:                OpBackendPreservesTableArrayBounds,
	OpTableArraySwapPairs:           OpBackendPreservesTableArrayBounds | OpBackendClearsTableArrayBounds,
	OpTableBoolArrayFill:            OpBackendClearsTableArrayBounds,
	OpTableIntArrayReversePrefix:    OpBackendClearsTableArrayBounds,
	OpTableIntArrayCopyPrefix:       OpBackendClearsTableArrayBounds,
	OpGetField:                      OpBackendPreservesFieldSvalsCache,
	OpGetFieldNumToFloat:            OpBackendPreservesFieldSvalsCache,
	OpFieldPolyLen:                  OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpSetField:                      OpBackendPreservesFieldSvalsCache | OpBackendClearsTableArrayBounds,
	OpGetGlobal:                     OpBackendClearsTableArrayBounds,
	OpSetGlobal:                     OpBackendClearsTableArrayBounds,
	OpGetUpval:                      OpBackendClearsTableArrayBounds,
	OpSetUpval:                      OpBackendClearsTableArrayBounds,
	OpBoxInt:                        OpBackendPreservesTableArrayBounds,
	OpBoxFloat:                      OpBackendPreservesTableArrayBounds,
	OpUnboxInt:                      OpBackendPreservesTableArrayBounds,
	OpUnboxFloat:                    OpBackendPreservesTableArrayBounds,
	OpNumToFloat:                    OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardType:                     OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardIntRange:                 OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardGlobalConst:              OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardConstString:              OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardTableKind:                OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardCalleeProto:              OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardFieldCalleeProto:         OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardShapeFieldType:           OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardShapeFieldTypeMask:       OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardShapeFieldVMClosure:      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardTruthy:                   OpBackendPreservesTableArrayBounds,
	OpCall:                          OpBackendClearsTableArrayBounds,
	OpCallFloor:                     OpBackendClearsTableArrayBounds,
	OpFieldCallFloor:                OpBackendClearsTableArrayBounds,
	OpResume:                        OpBackendClearsTableArrayBounds,
	OpSelf:                          OpBackendClearsTableArrayBounds | OpBackendInvalidatesShape,
	OpForPrep:                       OpBackendClearsTableArrayBounds,
	OpForLoop:                       OpBackendClearsTableArrayBounds,
	OpTForCall:                      OpBackendClearsTableArrayBounds,
	OpTForLoop:                      OpBackendClearsTableArrayBounds,
	OpClosure:                       OpBackendClearsTableArrayBounds,
	OpClose:                         OpBackendClearsTableArrayBounds,
	OpVararg:                        OpBackendClearsTableArrayBounds,
	OpTestSet:                       OpBackendClearsTableArrayBounds,
	OpGo:                            OpBackendClearsTableArrayBounds,
	OpMakeChan:                      OpBackendClearsTableArrayBounds,
	OpSend:                          OpBackendClearsTableArrayBounds,
	OpRecv:                          OpBackendClearsTableArrayBounds,
	OpNop:                           OpBackendPreservesTableArrayBounds | OpBackendPreservesScratchFPRCache,
	OpConcat:                        OpBackendClearsTableArrayBounds,
	OpStringConstLookup:             OpBackendClearsTableArrayBounds,
	OpStringFormatInt:               OpBackendClearsTableArrayBounds,
	OpStringFormatConst:             OpBackendClearsTableArrayBounds,
	OpStringSplitPart:               OpBackendClearsTableArrayBounds,
	OpStringSplitSubstr:             OpBackendClearsTableArrayBounds,
	OpStringSplitSubstrNumber:       OpBackendClearsTableArrayBounds,
	OpAppend:                        OpBackendClearsTableArrayBounds,
	OpPow:                           OpBackendClearsTableArrayBounds,
	OpGuardNonNil:                   OpBackendClearsTableArrayBounds,
}
