package methodjit

var opFieldShapeSplitInlineSafePolicies = [...]bool{
	OpConstInt:              true,
	OpConstFloat:            true,
	OpConstBool:             true,
	OpConstNil:              true,
	OpConstString:           true,
	OpAddInt:                true,
	OpSubInt:                true,
	OpMulInt:                true,
	OpModInt:                true,
	OpNegInt:                true,
	OpAddFloat:              true,
	OpSubFloat:              true,
	OpMulFloat:              true,
	OpDivFloat:              true,
	OpNegFloat:              true,
	OpEqInt:                 true,
	OpLtInt:                 true,
	OpLeInt:                 true,
	OpEqString:              true,
	OpLtFloat:               true,
	OpLeFloat:               true,
	OpFloor:                 true,
	OpNumToFloat:            true,
	OpFieldSvals:            true,
	OpFieldLoad:             true,
	OpFieldLoadNumToFloat:   true,
	OpFieldPolyLen:          true,
	OpGuardType:             true,
	OpGuardIntRange:         true,
	OpGuardCalleeProto:      true,
	OpGuardFieldCalleeProto: true,
	OpBranch:                true,
	OpJump:                  true,
	OpPhi:                   true,
	OpFieldStore:            true,
	OpTableArrayHeader:      true,
	OpTableArrayLen:         true,
	OpTableArrayData:        true,
	OpTableArrayLoad:        true,
	OpTableArrayStore:       true,
}

var opFieldShapePreEffectInlineSafePolicies = [...]bool{
	OpGetField:           true,
	OpGetFieldNumToFloat: true,
	OpGetTable:           true,
	OpSetTable:           true,
	OpAdd:                true,
	OpSub:                true,
	OpMul:                true,
	OpDiv:                true,
	OpMod:                true,
	OpUnm:                true,
	OpLen:                true,
	OpFloor:              true,
	OpNumToFloat:         true,
}

var opFieldShapeInlineSideEffectPolicies = [...]bool{
	OpFieldStore:      true,
	OpTableArrayStore: true,
	OpSetField:        true,
	OpSetTable:        true,
}

var opFieldShapePostEffectInlineUnsafePolicies = [...]bool{
	OpSetField:           true,
	OpGetField:           true,
	OpGetFieldNumToFloat: true,
	OpSetTable:           true,
	OpGetTable:           true,
	OpCall:               true,
	OpCallFloor:          true,
	OpFieldCallFloor:     true,
	OpResume:             true,
	OpYield:              true,
	OpSelf:               true,
}
