package methodjit

var opDirectDeoptWithoutFullFlushPolicies = [...]bool{
	OpGuardType:                true,
	OpGuardIntRange:            true,
	OpGuardGlobalConst:         true,
	OpGuardConstString:         true,
	OpGuardTableKind:           true,
	OpGuardCalleeProto:         true,
	OpGuardFieldCalleeProto:    true,
	OpGuardShapeFieldType:      true,
	OpGuardShapeFieldTypeMask:  true,
	OpGuardShapeFieldVMClosure: true,
	OpNumToFloat:               true,
	OpDivIntExact:              true,
	OpGetFieldNumToFloat:       true,
	OpFieldPolyLen:             true,
	OpFieldSvals:               true,
	OpFieldLoad:                true,
	OpFieldLoadNumToFloat:      true,
	OpMatrixGetF:               true,
	OpMatrixSetF:               true,
	OpMatrixFlat:               true,
	OpMatrixStride:             true,
	OpTableArrayHeader:         true,
	OpTableArrayLoad:           true,
	OpTableShapeID:             true,
	OpTableArrayStore:          true,
	OpTableArraySwap:           true,
	OpTableArraySwapPairs:      true,
	OpTableArrayNestedLoad:     true,
}
