package methodjit

func opSpecValuePolicyTables() []opSpecPolicyTable {
	return []opSpecPolicyTable{
		{"opNoSSAResultPolicies", opNoSSAResultPolicies},
		{"opRawIntResultPolicies", opRawIntResultPolicies},
		{"opRawTablePtrResultPolicies", opRawTablePtrResultPolicies},
		{"opRawDataPtrResultPolicies", opRawDataPtrResultPolicies},
		{"opRawFloatResultPolicies", opRawFloatResultPolicies},
		{"opMatrixNativePolicies", opMatrixNativePolicies},
		{"opMatrixLoweredOpPolicies", opMatrixLoweredOpPolicies},
		{"opMatrixRowLoweredOpPolicies", opMatrixRowLoweredOpPolicies},
		{"opMatrixRowConstLoweredOpPolicies", opMatrixRowConstLoweredOpPolicies},
		{"opMatrixNestedLoweredOpPolicies", opMatrixNestedLoweredOpPolicies},
		{"opTableArrayGPRInvariantPolicies", opTableArrayGPRInvariantPolicies},
		{"opTableArrayGPRInvariantRankPolicies", opTableArrayGPRInvariantRankPolicies},
		{"opTableArrayGPRInvariantUseMaskPolicies", opTableArrayGPRInvariantUseMaskPolicies},
		{"opTableArrayKeyArgIndexPolicies", opTableArrayKeyArgIndexPolicies},
		{"opTableArrayTableArgIndexPolicies", opTableArrayTableArgIndexPolicies},
		{"opTableArrayDataArgIndexPolicies", opTableArrayDataArgIndexPolicies},
		{"opTableArrayLenArgIndexPolicies", opTableArrayLenArgIndexPolicies},
		{"opTableArrayLoweredOpPolicies", opTableArrayLoweredOpPolicies},
		{"opTableArrayNestedLoweredOpPolicies", opTableArrayNestedLoweredOpPolicies},
		{"opTableArraySwapLoweredOpPolicies", opTableArraySwapLoweredOpPolicies},
		{"opTableIntArraySwapPairsBodyBenignPolicies", opTableIntArraySwapPairsBodyBenignPolicies},
		{"opTableIntArrayCopyPrefixBodyBenignPolicies", opTableIntArrayCopyPrefixBodyBenignPolicies},
		{"opTableIntArrayReverseBodyBenignPolicies", opTableIntArrayReverseBodyBenignPolicies},
		{"opFixedShapeArrayElementWriteRolePolicies", opFixedShapeArrayElementWriteRolePolicies},
		{"opFixedShapeArrayElementReadRolePolicies", opFixedShapeArrayElementReadRolePolicies},
		{"opFixedShapeReturnArrayElementRolePolicies", opFixedShapeReturnArrayElementRolePolicies},
		{"opLocalStringArrayTableUseRolePolicies", opLocalStringArrayTableUseRolePolicies},
		{"opLocalStringArrayTableArgIndexPolicies", opLocalStringArrayTableArgIndexPolicies},
		{"opReadonlyTableParamUseRolePolicies", opReadonlyTableParamUseRolePolicies},
		{"opInlineAllocationRolePolicies", opInlineAllocationRolePolicies},
		{"opInlineAllocationLoweredOpPolicies", opInlineAllocationLoweredOpPolicies},
	}
}
