package methodjit

var opFieldShapeSplitInlineSafePolicies = [...]bool{
	OpConstInt:              true,
	OpConstFloat:            true,
	OpConstBool:             true,
	OpConstNil:              true,
	OpConstString:           true,
	OpAddInt:                true,
	OpSubInt:                true,
	OpMulInt:                true,
	OpModInt:                true,
	OpNegInt:                true,
	OpAddFloat:              true,
	OpSubFloat:              true,
	OpMulFloat:              true,
	OpDivFloat:              true,
	OpNegFloat:              true,
	OpEqInt:                 true,
	OpLtInt:                 true,
	OpLeInt:                 true,
	OpEqString:              true,
	OpLtFloat:               true,
	OpLeFloat:               true,
	OpFloor:                 true,
	OpNumToFloat:            true,
	OpFieldSvals:            true,
	OpFieldLoad:             true,
	OpFieldLoadNumToFloat:   true,
	OpFieldPolyLen:          true,
	OpGuardType:             true,
	OpGuardIntRange:         true,
	OpGuardCalleeProto:      true,
	OpGuardFieldCalleeProto: true,
	OpBranch:                true,
	OpJump:                  true,
	OpPhi:                   true,
	OpFieldStore:            true,
	OpTableArrayHeader:      true,
	OpTableArrayLen:         true,
	OpTableArrayData:        true,
	OpTableArrayLoad:        true,
	OpTableArrayStore:       true,
}

var opFieldShapePreEffectInlineSafePolicies = [...]bool{
	OpGetField:           true,
	OpGetFieldNumToFloat: true,
	OpGetTable:           true,
	OpSetTable:           true,
	OpAdd:                true,
	OpSub:                true,
	OpMul:                true,
	OpDiv:                true,
	OpMod:                true,
	OpUnm:                true,
	OpLen:                true,
	OpFloor:              true,
	OpNumToFloat:         true,
}

var opFieldShapeInlineSideEffectPolicies = [...]bool{
	OpFieldStore:      true,
	OpTableArrayStore: true,
	OpSetField:        true,
	OpSetTable:        true,
}

var opFieldShapePostEffectInlineUnsafePolicies = [...]bool{
	OpSetField:           true,
	OpGetField:           true,
	OpGetFieldNumToFloat: true,
	OpSetTable:           true,
	OpGetTable:           true,
	OpCall:               true,
	OpCallFloor:          true,
	OpFieldCallFloor:     true,
	OpResume:             true,
	OpYield:              true,
	OpSelf:               true,
}

var opGlobalConstUnsafePolicies = [...]bool{
	OpCall:      true,
	OpResume:    true,
	OpYield:     true,
	OpSelf:      true,
	OpSetGlobal: true,
	OpSetUpval:  true,
	OpGo:        true,
	OpSend:      true,
	OpRecv:      true,
}

var opNestedCallLikePolicies = [...]bool{
	OpCall:           true,
	OpCallFloor:      true,
	OpFieldCallFloor: true,
	OpResume:         true,
	OpYield:          true,
	OpTForCall:       true,
	OpGo:             true,
}

var opLoadElimConstCSEPolicies = [...]bool{
	OpConstInt:    true,
	OpConstFloat:  true,
	OpConstBool:   true,
	OpConstNil:    true,
	OpConstString: true,
}

var opLiteralConstPolicies = [...]bool{
	OpConstInt:    true,
	OpConstFloat:  true,
	OpConstBool:   true,
	OpConstNil:    true,
	OpConstString: true,
}

var opLoadElimPureCSEPolicies = [...]bool{
	OpAddInt:       true,
	OpSubInt:       true,
	OpMulInt:       true,
	OpModInt:       true,
	OpDivIntExact:  true,
	OpNegInt:       true,
	OpAddFloat:     true,
	OpSubFloat:     true,
	OpMulFloat:     true,
	OpDivFloat:     true,
	OpNegFloat:     true,
	OpNumToFloat:   true,
	OpSqrt:         true,
	OpFloor:        true,
	OpFMA:          true,
	OpFMSUB:        true,
	OpEqInt:        true,
	OpLtInt:        true,
	OpLeInt:        true,
	OpModZeroInt:   true,
	OpLtFloat:      true,
	OpLeFloat:      true,
	OpEqString:     true,
	OpTableShapeID: true,
}

var opLoadElimShapeFactKillerPolicies = [...]bool{
	OpSetField:                   true,
	OpSetTable:                   true,
	OpTableArrayStore:            true,
	OpTableArraySwap:             true,
	OpTableArraySwapPairs:        true,
	OpTableBoolArrayFill:         true,
	OpTableIntArrayReversePrefix: true,
	OpTableIntArrayCopyPrefix:    true,
	OpAppend:                     true,
	OpSetList:                    true,
	OpCall:                       true,
	OpResume:                     true,
	OpSelf:                       true,
}

var opFieldSvalsCrossBlockBarrierPolicies = [...]bool{
	OpCall:           true,
	OpCallFloor:      true,
	OpFieldCallFloor: true,
	OpResume:         true,
	OpYield:          true,
	OpSelf:           true,
	OpSetGlobal:      true,
	OpSetUpval:       true,
	OpSetTable:       true,
	OpSetList:        true,
	OpAppend:         true,
}

var opFieldSvalsGlobalBarrierPolicies = [...]bool{
	OpSetTable:       true,
	OpSetList:        true,
	OpAppend:         true,
	OpCall:           true,
	OpCallFloor:      true,
	OpFieldCallFloor: true,
	OpResume:         true,
	OpYield:          true,
	OpSelf:           true,
	OpSetGlobal:      true,
	OpSetUpval:       true,
}

var opFieldLenFoldBarrierPolicies = [...]bool{
	OpCall:                true,
	OpSetField:            true,
	OpFieldStore:          true,
	OpSetTable:            true,
	OpTableArrayStore:     true,
	OpTableArraySwap:      true,
	OpTableArraySwapPairs: true,
	OpSetGlobal:           true,
	OpSetUpval:            true,
	OpAppend:              true,
	OpSetList:             true,
}

var opFieldCallPolyLenFusionBarrierPolicies = [...]bool{
	OpSetField:                   true,
	OpSetTable:                   true,
	OpSetList:                    true,
	OpAppend:                     true,
	OpTableArrayStore:            true,
	OpTableArraySwap:             true,
	OpTableArraySwapPairs:        true,
	OpTableBoolArrayFill:         true,
	OpTableIntArrayReversePrefix: true,
	OpTableIntArrayCopyPrefix:    true,
	OpCall:                       true,
	OpCallFloor:                  true,
	OpFieldCallFloor:             true,
	OpResume:                     true,
	OpYield:                      true,
	OpSelf:                       true,
	OpGo:                         true,
	OpSend:                       true,
	OpRecv:                       true,
	OpReturn:                     true,
	OpJump:                       true,
	OpBranch:                     true,
}
