package methodjit

var opBackendPolicies = [...]OpBackendPolicy{
	OpConstInt:                      OpBackendPreservesTableArrayBounds,
	OpConstFloat:                    OpBackendPreservesTableArrayBounds,
	OpConstBool:                     OpBackendPreservesTableArrayBounds,
	OpConstNil:                      OpBackendPreservesTableArrayBounds,
	OpConstString:                   OpBackendPreservesTableArrayBounds,
	OpLoadSlot:                      OpBackendPreservesTableArrayBounds,
	OpStoreSlot:                     OpBackendPreservesTableArrayBounds,
	OpAdd:                           OpBackendPreservesTableArrayBounds,
	OpSub:                           OpBackendPreservesTableArrayBounds,
	OpMul:                           OpBackendPreservesTableArrayBounds,
	OpDiv:                           OpBackendPreservesTableArrayBounds,
	OpMod:                           OpBackendPreservesTableArrayBounds,
	OpUnm:                           OpBackendPreservesTableArrayBounds,
	OpNot:                           OpBackendPreservesTableArrayBounds,
	OpLen:                           OpBackendClearsTableArrayBounds,
	OpAddInt:                        OpBackendPreservesTableArrayBounds,
	OpSubInt:                        OpBackendPreservesTableArrayBounds,
	OpMulInt:                        OpBackendPreservesTableArrayBounds,
	OpModInt:                        OpBackendPreservesTableArrayBounds,
	OpNegInt:                        OpBackendPreservesTableArrayBounds,
	OpAddFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpSubFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpMulFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpDivFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpNegFloat:                      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpSqrt:                          OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpFloor:                         OpBackendPreservesTableArrayBounds,
	OpFMA:                           OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpFMSUB:                         OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCacheForFloatResult | OpBackendPreservesScratchFPRCacheForFloatResult,
	OpComplexEscapeInSet:            OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpComplexEscapeRowCount:         OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpRecordArrayLoopSpecialization: OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpEq:                            OpBackendPreservesTableArrayBounds,
	OpLt:                            OpBackendPreservesTableArrayBounds,
	OpLe:                            OpBackendPreservesTableArrayBounds,
	OpEqInt:                         OpBackendPreservesTableArrayBounds,
	OpLtInt:                         OpBackendPreservesTableArrayBounds,
	OpLeInt:                         OpBackendPreservesTableArrayBounds,
	OpModZeroInt:                    OpBackendPreservesTableArrayBounds,
	OpLtFloat:                       OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache | OpBackendPreservesScratchFPRCache,
	OpLeFloat:                       OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache | OpBackendPreservesScratchFPRCache,
	OpEqString:                      OpBackendPreservesTableArrayBounds,
	OpStringFormatConstLen:          OpBackendPreservesTableArrayBounds | OpBackendClearsTableArrayBounds,
	OpNewTable:                      0,
	OpSetTable:                      OpBackendClearsTableArrayBounds | OpBackendInvalidatesShape,
	OpTableArrayHeader:              OpBackendPreservesTableArrayBounds,
	OpTableArrayLen:                 OpBackendPreservesTableArrayBounds,
	OpTableArrayData:                OpBackendPreservesTableArrayBounds,
	OpTableArrayLoad:                OpBackendPreservesTableArrayBounds,
	OpTableShapeID:                  OpBackendPreservesTableArrayBounds,
	OpTableArrayStore:               OpBackendPreservesTableArrayBounds,
	OpTableArraySwap:                OpBackendPreservesTableArrayBounds,
	OpTableArraySwapPairs:           OpBackendPreservesTableArrayBounds | OpBackendClearsTableArrayBounds,
	OpTableBoolArrayFill:            OpBackendClearsTableArrayBounds,
	OpTableIntArrayReversePrefix:    OpBackendClearsTableArrayBounds,
	OpTableIntArrayCopyPrefix:       OpBackendClearsTableArrayBounds,
	OpGetField:                      OpBackendPreservesFieldSvalsCache,
	OpGetFieldNumToFloat:            OpBackendPreservesFieldSvalsCache,
	OpFieldPolyLen:                  OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpSetField:                      OpBackendPreservesFieldSvalsCache | OpBackendClearsTableArrayBounds,
	OpGetGlobal:                     OpBackendClearsTableArrayBounds,
	OpSetGlobal:                     OpBackendClearsTableArrayBounds,
	OpGetUpval:                      OpBackendClearsTableArrayBounds,
	OpSetUpval:                      OpBackendClearsTableArrayBounds,
	OpBoxInt:                        OpBackendPreservesTableArrayBounds,
	OpBoxFloat:                      OpBackendPreservesTableArrayBounds,
	OpUnboxInt:                      OpBackendPreservesTableArrayBounds,
	OpUnboxFloat:                    OpBackendPreservesTableArrayBounds,
	OpNumToFloat:                    OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardType:                     OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardIntRange:                 OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardGlobalConst:              OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardConstString:              OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardTableKind:                OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardCalleeProto:              OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardFieldCalleeProto:         OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardShapeFieldType:           OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardShapeFieldTypeMask:       OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardShapeFieldVMClosure:      OpBackendPreservesTableArrayBounds | OpBackendPreservesFieldSvalsCache,
	OpGuardTruthy:                   OpBackendPreservesTableArrayBounds,
	OpCall:                          OpBackendClearsTableArrayBounds,
	OpCallFloor:                     OpBackendClearsTableArrayBounds,
	OpFieldCallFloor:                OpBackendClearsTableArrayBounds,
	OpResume:                        OpBackendClearsTableArrayBounds,
	OpSelf:                          OpBackendClearsTableArrayBounds | OpBackendInvalidatesShape,
	OpForPrep:                       OpBackendClearsTableArrayBounds,
	OpForLoop:                       OpBackendClearsTableArrayBounds,
	OpTForCall:                      OpBackendClearsTableArrayBounds,
	OpTForLoop:                      OpBackendClearsTableArrayBounds,
	OpClosure:                       OpBackendClearsTableArrayBounds,
	OpClose:                         OpBackendClearsTableArrayBounds,
	OpVararg:                        OpBackendClearsTableArrayBounds,
	OpTestSet:                       OpBackendClearsTableArrayBounds,
	OpGo:                            OpBackendClearsTableArrayBounds,
	OpMakeChan:                      OpBackendClearsTableArrayBounds,
	OpSend:                          OpBackendClearsTableArrayBounds,
	OpRecv:                          OpBackendClearsTableArrayBounds,
	OpNop:                           OpBackendPreservesTableArrayBounds | OpBackendPreservesScratchFPRCache,
	OpConcat:                        OpBackendClearsTableArrayBounds,
	OpStringConstLookup:             OpBackendClearsTableArrayBounds,
	OpStringFormatInt:               OpBackendClearsTableArrayBounds,
	OpStringFormatConst:             OpBackendClearsTableArrayBounds,
	OpStringSplitPart:               OpBackendClearsTableArrayBounds,
	OpStringSplitSubstr:             OpBackendClearsTableArrayBounds,
	OpStringSplitSubstrNumber:       OpBackendClearsTableArrayBounds,
	OpAppend:                        OpBackendClearsTableArrayBounds,
	OpPow:                           OpBackendClearsTableArrayBounds,
	OpGuardNonNil:                   OpBackendClearsTableArrayBounds,
}

var opKeepUnusedPolicies = [...]bool{
	OpJump:                          true,
	OpBranch:                        true,
	OpReturn:                        true,
	OpStoreSlot:                     true,
	OpSetGlobal:                     true,
	OpSetUpval:                      true,
	OpSetTable:                      true,
	OpTableArrayStore:               true,
	OpTableArraySwap:                true,
	OpTableArraySwapPairs:           true,
	OpTableBoolArrayFill:            true,
	OpTableIntArrayReversePrefix:    true,
	OpTableIntArrayCopyPrefix:       true,
	OpRecordArrayLoopSpecialization: true,
	OpFieldStore:                    true,
	OpSetField:                      true,
	OpSetList:                       true,
	OpAppend:                        true,
	OpMatrixSetF:                    true,
	OpMatrixStoreFAt:                true,
	OpMatrixStoreFRow:               true,
	OpMatrixStoreFRowConst:          true,
	OpCall:                          true,
	OpCallFloor:                     true,
	OpFieldCallFloor:                true,
	OpResume:                        true,
	OpYield:                         true,
	OpSelf:                          true,
	OpGuardType:                     true,
	OpGuardIntRange:                 true,
	OpGuardGlobalConst:              true,
	OpGuardConstString:              true,
	OpGuardTableKind:                true,
	OpGuardCalleeProto:              true,
	OpGuardFieldCalleeProto:         true,
	OpGuardShapeFieldType:           true,
	OpGuardShapeFieldTypeMask:       true,
	OpGuardShapeFieldVMClosure:      true,
	OpGuardNonNil:                   true,
	OpGuardTruthy:                   true,
	OpForPrep:                       true,
	OpForLoop:                       true,
	OpTForCall:                      true,
	OpTForLoop:                      true,
	OpClosure:                       true,
	OpClose:                         true,
	OpGo:                            true,
	OpMakeChan:                      true,
	OpSend:                          true,
	OpRecv:                          true,
}

var opNativeReplayMayExitPolicies = [...]bool{
	OpCall:                       true,
	OpCallFloor:                  true,
	OpFieldCallFloor:             true,
	OpSelf:                       true,
	OpNewTable:                   true,
	OpNewFixedTable:              true,
	OpGetTable:                   true,
	OpSetTable:                   true,
	OpTableArrayHeader:           true,
	OpTableArrayLen:              true,
	OpTableArrayData:             true,
	OpTableArrayLoad:             true,
	OpTableArrayStore:            true,
	OpTableArraySwap:             true,
	OpTableArraySwapPairs:        true,
	OpTableBoolArrayFill:         true,
	OpTableBoolArrayCount:        true,
	OpTableIntArrayReversePrefix: true,
	OpTableIntArrayCopyPrefix:    true,
	OpTableArrayNestedLoad:       true,
	OpGetField:                   true,
	OpGetFieldNumToFloat:         true,
	OpFieldPolyLen:               true,
	OpSetField:                   true,
	OpFieldStore:                 true,
	OpSetList:                    true,
	OpAppend:                     true,
	OpGetGlobal:                  true,
	OpSetGlobal:                  true,
	OpGetUpval:                   true,
	OpSetUpval:                   true,
	OpConstString:                true,
	OpConcat:                     true,
	OpStringConstLookup:          true,
	OpStringFormatInt:            true,
	OpStringFormatConst:          true,
	OpStringFormatConstLen:       true,
	OpGetTableStringFormatInt:    true,
	OpStringSplitPart:            true,
	OpStringSplitSubstr:          true,
	OpStringSplitSubstrNumber:    true,
	OpLen:                        true,
	OpPow:                        true,
	OpFloor:                      true,
	OpClosure:                    true,
	OpClose:                      true,
	OpVararg:                     true,
	OpTForCall:                   true,
	OpTForLoop:                   true,
	OpGo:                         true,
	OpMakeChan:                   true,
	OpSend:                       true,
	OpRecv:                       true,
	OpGuardType:                  true,
	OpGuardIntRange:              true,
	OpGuardGlobalConst:           true,
	OpGuardConstString:           true,
	OpGuardTableKind:             true,
	OpGuardCalleeProto:           true,
	OpGuardFieldCalleeProto:      true,
	OpGuardShapeFieldType:        true,
	OpGuardShapeFieldTypeMask:    true,
	OpGuardShapeFieldVMClosure:   true,
	OpGuardNonNil:                true,
	OpGuardTruthy:                true,
	OpNumToFloat:                 true,
	OpDivIntExact:                true,
	OpMatrixDense:                true,
	OpMatrixGetF:                 true,
	OpMatrixSetF:                 true,
	OpMatrixFlat:                 true,
	OpMatrixStride:               true,
	OpAddInt:                     true,
	OpSubInt:                     true,
	OpMulInt:                     true,
	OpNegInt:                     true,
	OpModInt:                     true,
	OpModZeroInt:                 true,
}

var opNativeReplayVisibleSideEffectPolicies = [...]bool{
	OpSetGlobal:            true,
	OpSetUpval:             true,
	OpMatrixSetF:           true,
	OpMatrixStoreFAt:       true,
	OpMatrixStoreFRow:      true,
	OpMatrixStoreFRowConst: true,
	OpClose:                true,
	OpGo:                   true,
	OpSend:                 true,
	OpRecv:                 true,
}

var opNativeReplayVisibleTableMutationPolicies = [...]bool{
	OpSetTable:                   true,
	OpTableArrayStore:            true,
	OpTableArraySwap:             true,
	OpTableArraySwapPairs:        true,
	OpTableBoolArrayFill:         true,
	OpTableIntArrayReversePrefix: true,
	OpTableIntArrayCopyPrefix:    true,
	OpSetField:                   true,
	OpFieldStore:                 true,
	OpSetList:                    true,
	OpAppend:                     true,
}

var opNativeCalleeResumeUnsafePolicies = [...]bool{
	OpSetGlobal: true,
	OpSetUpval:  true,
	OpClose:     true,
	OpGo:        true,
	OpSend:      true,
	OpRecv:      true,
}

var opRestartVisibleSideEffectPolicies = [...]bool{
	OpCall:                true,
	OpSetGlobal:           true,
	OpSetTable:            true,
	OpTableArrayStore:     true,
	OpTableArraySwap:      true,
	OpTableArraySwapPairs: true,
	OpSetField:            true,
	OpNewTable:            true,
	OpNewFixedTable:       true,
	OpSetList:             true,
	OpAppend:              true,
	OpSelf:                true,
	OpSetUpval:            true,
	OpGo:                  true,
	OpMakeChan:            true,
	OpSend:                true,
	OpRecv:                true,
	OpClosure:             true,
	OpClose:               true,
	OpVararg:              true,
	OpConcat:              true,
	OpLen:                 true,
	OpPow:                 true,
	OpTForCall:            true,
	OpTForLoop:            true,
}

func applyOpSpecBackendPolicies(op Op, spec *OpSpec) {
	if int(op) < len(opBackendPolicies) {
		spec.BackendPolicy = opBackendPolicies[op]
	}
	if int(op) < len(opKeepUnusedPolicies) {
		spec.KeepUnused = opKeepUnusedPolicies[op]
	}
	if int(op) < len(opNativeReplayMayExitPolicies) {
		spec.NativeReplayMayExit = opNativeReplayMayExitPolicies[op]
	}
	if int(op) < len(opNativeReplayVisibleSideEffectPolicies) {
		spec.NativeReplayVisibleSideEffect = opNativeReplayVisibleSideEffectPolicies[op]
	}
	if int(op) < len(opNativeReplayVisibleTableMutationPolicies) {
		spec.NativeReplayVisibleTableMutation = opNativeReplayVisibleTableMutationPolicies[op]
	}
	if int(op) < len(opNativeCalleeResumeUnsafePolicies) {
		spec.NativeCalleeResumeUnsafe = opNativeCalleeResumeUnsafePolicies[op]
	}
	if int(op) < len(opRestartVisibleSideEffectPolicies) {
		spec.RestartVisibleSideEffect = opRestartVisibleSideEffectPolicies[op]
	}
}
