package methodjit

var opRestartVisibleSideEffectPolicies = [...]bool{
	OpCall:                true,
	OpSetGlobal:           true,
	OpSetTable:            true,
	OpTableArrayStore:     true,
	OpTableArraySwap:      true,
	OpTableArraySwapPairs: true,
	OpSetField:            true,
	OpNewTable:            true,
	OpNewFixedTable:       true,
	OpSetList:             true,
	OpAppend:              true,
	OpSelf:                true,
	OpSetUpval:            true,
	OpGo:                  true,
	OpMakeChan:            true,
	OpSend:                true,
	OpRecv:                true,
	OpClosure:             true,
	OpClose:               true,
	OpVararg:              true,
	OpConcat:              true,
	OpLen:                 true,
	OpPow:                 true,
	OpTForCall:            true,
	OpTForLoop:            true,
}
