package methodjit

var opNativeReplayMayExitPolicies = [...]bool{
	OpCall:                       true,
	OpCallFloor:                  true,
	OpFieldCallFloor:             true,
	OpSelf:                       true,
	OpNewTable:                   true,
	OpNewFixedTable:              true,
	OpGetTable:                   true,
	OpSetTable:                   true,
	OpTableArrayHeader:           true,
	OpTableArrayLen:              true,
	OpTableArrayData:             true,
	OpTableArrayLoad:             true,
	OpTableArrayStore:            true,
	OpTableArraySwap:             true,
	OpTableArraySwapPairs:        true,
	OpTableBoolArrayFill:         true,
	OpTableBoolArrayCount:        true,
	OpTableIntArrayReversePrefix: true,
	OpTableIntArrayCopyPrefix:    true,
	OpTableArrayNestedLoad:       true,
	OpGetField:                   true,
	OpGetFieldNumToFloat:         true,
	OpFieldPolyLen:               true,
	OpSetField:                   true,
	OpFieldStore:                 true,
	OpSetList:                    true,
	OpAppend:                     true,
	OpGetGlobal:                  true,
	OpSetGlobal:                  true,
	OpGetUpval:                   true,
	OpSetUpval:                   true,
	OpConstString:                true,
	OpConcat:                     true,
	OpStringConstLookup:          true,
	OpStringFormatInt:            true,
	OpStringFormatConst:          true,
	OpStringFormatConstLen:       true,
	OpGetTableStringFormatInt:    true,
	OpStringSplitPart:            true,
	OpStringSplitSubstr:          true,
	OpStringSplitSubstrNumber:    true,
	OpLen:                        true,
	OpPow:                        true,
	OpFloor:                      true,
	OpClosure:                    true,
	OpClose:                      true,
	OpVararg:                     true,
	OpTForCall:                   true,
	OpTForLoop:                   true,
	OpGo:                         true,
	OpMakeChan:                   true,
	OpSend:                       true,
	OpRecv:                       true,
	OpGuardType:                  true,
	OpGuardIntRange:              true,
	OpGuardGlobalConst:           true,
	OpGuardConstString:           true,
	OpGuardTableKind:             true,
	OpGuardCalleeProto:           true,
	OpGuardFieldCalleeProto:      true,
	OpGuardShapeFieldType:        true,
	OpGuardShapeFieldTypeMask:    true,
	OpGuardShapeFieldVMClosure:   true,
	OpGuardNonNil:                true,
	OpGuardTruthy:                true,
	OpNumToFloat:                 true,
	OpDivIntExact:                true,
	OpMatrixDense:                true,
	OpMatrixGetF:                 true,
	OpMatrixSetF:                 true,
	OpMatrixFlat:                 true,
	OpMatrixStride:               true,
	OpQEvalPipelinePlan:          true,
	OpQEvalSessionEval:           true,
	OpAddInt:                     true,
	OpSubInt:                     true,
	OpMulInt:                     true,
	OpNegInt:                     true,
	OpModInt:                     true,
	OpModZeroInt:                 true,
}

var opNativeReplayVisibleSideEffectPolicies = [...]bool{
	OpSetGlobal:            true,
	OpSetUpval:             true,
	OpMatrixSetF:           true,
	OpMatrixStoreFAt:       true,
	OpMatrixStoreFRow:      true,
	OpMatrixStoreFRowConst: true,
	OpClose:                true,
	OpGo:                   true,
	OpSend:                 true,
	OpRecv:                 true,
}

var opNativeReplayVisibleTableMutationPolicies = [...]bool{
	OpSetTable:                   true,
	OpTableArrayStore:            true,
	OpTableArraySwap:             true,
	OpTableArraySwapPairs:        true,
	OpTableBoolArrayFill:         true,
	OpTableIntArrayReversePrefix: true,
	OpTableIntArrayCopyPrefix:    true,
	OpSetField:                   true,
	OpFieldStore:                 true,
	OpSetList:                    true,
	OpAppend:                     true,
}

var opNativeCalleeResumeUnsafePolicies = [...]bool{
	OpSetGlobal: true,
	OpSetUpval:  true,
	OpClose:     true,
	OpGo:        true,
	OpSend:      true,
	OpRecv:      true,
}
