package methodjit

var opSpecs = [...]OpSpec{
	OpConstInt:                      opSpec("ConstInt", OpEmitterConst, OpArgAux, OpSideEffectNone, false),
	OpConstFloat:                    opSpec("ConstFloat", OpEmitterConst, OpArgAux, OpSideEffectNone, false),
	OpConstBool:                     opSpec("ConstBool", OpEmitterConst, OpArgAux, OpSideEffectNone, false),
	OpConstNil:                      opSpec("ConstNil", OpEmitterConst, OpArgNone, OpSideEffectNone, false),
	OpConstString:                   opSpec("ConstString", OpEmitterConst, OpArgAux, OpSideEffectRead, false),
	OpLoadSlot:                      opSpec("LoadSlot", OpEmitterSlot, OpArgAux, OpSideEffectRead, false),
	OpStoreSlot:                     opSpec("StoreSlot", OpEmitterSlot, OpArgFixedAux, OpSideEffectWrite, false),
	OpAdd:                           opSpec("Add", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpSub:                           opSpec("Sub", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpMul:                           opSpec("Mul", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpDiv:                           opSpec("Div", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpMod:                           opSpec("Mod", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpPow:                           opSpec("Pow", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpUnm:                           opSpec("Unm", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpNot:                           opSpec("Not", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpLen:                           opSpec("Len", OpEmitterArithmetic, OpArgFixed, OpSideEffectRead, true),
	OpAddInt:                        opSpec("AddInt", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpSubInt:                        opSpec("SubInt", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpMulInt:                        opSpec("MulInt", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpModInt:                        opSpec("ModInt", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpDivIntExact:                   opSpec("DivIntExact", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpNegInt:                        opSpec("NegInt", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpAddFloat:                      opSpec("AddFloat", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpSubFloat:                      opSpec("SubFloat", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpMulFloat:                      opSpec("MulFloat", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpDivFloat:                      opSpec("DivFloat", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpNegFloat:                      opSpec("NegFloat", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpSqrt:                          opSpec("Sqrt", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpFloor:                         opSpec("Floor", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, true),
	OpMatrixDense:                   opSpec("MatrixDense", OpEmitterMatrix, OpArgFixed, OpSideEffectAllocate, true),
	OpMatrixGetF:                    opSpec("MatrixGetF", OpEmitterMatrix, OpArgFixed, OpSideEffectRead, true),
	OpMatrixSetF:                    opSpec("MatrixSetF", OpEmitterMatrix, OpArgFixed, OpSideEffectWrite, true),
	OpMatrixFlat:                    opSpec("MatrixFlat", OpEmitterMatrix, OpArgFixed, OpSideEffectRead, true),
	OpMatrixStride:                  opSpec("MatrixStride", OpEmitterMatrix, OpArgFixed, OpSideEffectRead, true),
	OpMatrixLoadFAt:                 opSpec("MatrixLoadFAt", OpEmitterMatrix, OpArgFixed, OpSideEffectRead, false),
	OpMatrixStoreFAt:                opSpec("MatrixStoreFAt", OpEmitterMatrix, OpArgFixed, OpSideEffectWrite, false),
	OpMatrixRowPtr:                  opSpec("MatrixRowPtr", OpEmitterMatrix, OpArgFixed, OpSideEffectNone, false),
	OpMatrixLoadFRow:                opSpec("MatrixLoadFRow", OpEmitterMatrix, OpArgFixed, OpSideEffectRead, false),
	OpMatrixStoreFRow:               opSpec("MatrixStoreFRow", OpEmitterMatrix, OpArgFixed, OpSideEffectWrite, false),
	OpMatrixLoadFRowConst:           opSpec("MatrixLoadFRowConst", OpEmitterMatrix, OpArgFixedAux, OpSideEffectRead, false),
	OpMatrixStoreFRowConst:          opSpec("MatrixStoreFRowConst", OpEmitterMatrix, OpArgFixedAux, OpSideEffectWrite, false),
	OpFMA:                           opSpec("FMA", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpFMSUB:                         opSpec("FMSUB", OpEmitterArithmetic, OpArgFixed, OpSideEffectNone, false),
	OpComplexEscapeInSet:            opSpec("ComplexEscapeInSet", OpEmitterSpecialization, OpArgFixedAux, OpSideEffectNone, false),
	OpComplexEscapeRowCount:         opSpec("ComplexEscapeRowCount", OpEmitterSpecialization, OpArgFixedAux, OpSideEffectNone, false),
	OpRecordArrayLoopSpecialization: opSpecArgCount(opSpec("RecordArrayLoopSpecialization", OpEmitterSpecialization, OpArgVariadicAux, OpSideEffectReadWrite, true), OpRangedCount(3, 16)),
	OpEq:                            opSpec("Eq", OpEmitterCompare, OpArgFixed, OpSideEffectNone, true),
	OpLt:                            opSpec("Lt", OpEmitterCompare, OpArgFixed, OpSideEffectNone, true),
	OpLe:                            opSpec("Le", OpEmitterCompare, OpArgFixed, OpSideEffectNone, true),
	OpEqInt:                         opSpec("EqInt", OpEmitterCompare, OpArgFixed, OpSideEffectNone, false),
	OpLtInt:                         opSpec("LtInt", OpEmitterCompare, OpArgFixed, OpSideEffectNone, false),
	OpLeInt:                         opSpec("LeInt", OpEmitterCompare, OpArgFixed, OpSideEffectNone, false),
	OpModZeroInt:                    opSpec("ModZeroInt", OpEmitterCompare, OpArgFixedAux, OpSideEffectNone, false),
	OpLtFloat:                       opSpec("LtFloat", OpEmitterCompare, OpArgFixed, OpSideEffectNone, false),
	OpLeFloat:                       opSpec("LeFloat", OpEmitterCompare, OpArgFixed, OpSideEffectNone, false),
	OpEqString:                      opSpec("EqString", OpEmitterCompare, OpArgFixed, OpSideEffectNone, false),
	OpConcat:                        opSpec("Concat", OpEmitterString, OpArgVariadic, OpSideEffectRead, true),
	OpStringConstLookup:             opSpec("StringConstLookup", OpEmitterString, OpArgFixedAux, OpSideEffectRead, true),
	OpStringFormatInt:               opSpec("StringFormatInt", OpEmitterString, OpArgFixedAux, OpSideEffectCall, true),
	OpStringFormatConst:             opSpec("StringFormatConst", OpEmitterString, OpArgVariadicAux, OpSideEffectCall, true),
	OpStringFormatConstLen:          opSpec("StringFormatConstLen", OpEmitterString, OpArgVariadicAux, OpSideEffectCall, true),
	OpGetTableStringFormatInt:       opSpec("GetTableStringFormatInt", OpEmitterString, OpArgFixedAux, OpSideEffectCall, true),
	OpStringSplitPart:               opSpec("StringSplitPart", OpEmitterString, OpArgFixedAux, OpSideEffectCall, true),
	OpStringSplitSubstr:             opSpec("StringSplitSubstr", OpEmitterString, OpArgFixedAux, OpSideEffectCall, true),
	OpStringSplitSubstrNumber:       opSpec("StringSplitSubstrNumber", OpEmitterString, OpArgFixedAux, OpSideEffectCall, true),
	OpNewTable:                      opSpec("NewTable", OpEmitterTable, OpArgAux, OpSideEffectAllocate, true),
	OpNewFixedTable:                 opSpec("NewFixedTable", OpEmitterTable, OpArgVariadicAux, OpSideEffectAllocate, true),
	OpGetTable:                      opSpec("GetTable", OpEmitterTable, OpArgFixed, OpSideEffectRead, true),
	OpSetTable:                      opSpecArgCount(opSpec("SetTable", OpEmitterTable, OpArgFixed, OpSideEffectWrite, true), OpFixedCount(3)),
	OpTableArrayHeader:              opSpec("TableArrayHeader", OpEmitterTable, OpArgFixedAux, OpSideEffectRead, true),
	OpTableArrayLen:                 opSpec("TableArrayLen", OpEmitterTable, OpArgFixed, OpSideEffectRead, false),
	OpTableArrayData:                opSpec("TableArrayData", OpEmitterTable, OpArgFixed, OpSideEffectRead, false),
	OpTableArrayLoad:                opSpec("TableArrayLoad", OpEmitterTable, OpArgFixed, OpSideEffectRead, true),
	OpTableShapeID:                  opSpecArgCount(opSpec("TableShapeID", OpEmitterTable, OpArgFixed, OpSideEffectRead, true), OpFixedCount(1)),
	OpTableArrayStore:               opSpecArgCount(opSpec("TableArrayStore", OpEmitterTable, OpArgFixed, OpSideEffectWrite, true), OpRangedCount(5, 6)),
	OpTableArraySwap:                opSpec("TableArraySwap", OpEmitterTable, OpArgFixed, OpSideEffectWrite, true),
	OpTableArraySwapPairs:           opSpecArgCount(opSpec("TableArraySwapPairs", OpEmitterTable, OpArgFixed, OpSideEffectWrite, true), OpFixedCount(3)),
	OpTableBoolArrayFill:            opSpec("TableBoolArrayFill", OpEmitterTable, OpArgVariadicAux, OpSideEffectWrite, true),
	OpTableBoolArrayCount:           opSpec("TableBoolArrayCount", OpEmitterTable, OpArgFixed, OpSideEffectRead, true),
	OpTableIntArrayReversePrefix:    opSpec("TableIntArrayReversePrefix", OpEmitterTable, OpArgFixed, OpSideEffectWrite, true),
	OpTableIntArrayCopyPrefix:       opSpec("TableIntArrayCopyPrefix", OpEmitterTable, OpArgFixed, OpSideEffectWrite, true),
	OpTableArrayNestedLoad:          opSpec("TableNestedLoad", OpEmitterTable, OpArgFixedAux, OpSideEffectRead, true),
	OpFrameLen:                      opSpecArgCount(opSpec("FrameLen", OpEmitterTable, OpArgFixed, OpSideEffectRead, true), OpFixedCount(1)),
	OpFrameColumn:                   opSpecArgCount(opSpec("FrameColumn", OpEmitterTable, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(1)),
	OpFrameProject:                  opSpecArgCount(opSpec("FrameProject", OpEmitterTable, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(1)),
	OpFrameFilter:                   opSpecArgCount(opSpec("FrameFilter", OpEmitterTable, OpArgFixed, OpSideEffectRead, true), OpFixedCount(2)),
	OpFrameGather:                   opSpecArgCount(opSpec("FrameGather", OpEmitterTable, OpArgFixed, OpSideEffectRead, true), OpFixedCount(2)),
	OpFrameSlice:                    opSpecArgCount(opSpec("FrameSlice", OpEmitterTable, OpArgFixed, OpSideEffectRead, true), OpFixedCount(2)),
	OpVectorGather:                  opSpecArgCount(opSpec("VectorGather", OpEmitterTable, OpArgFixed, OpSideEffectRead, true), OpFixedCount(2)),
	OpVectorCompare:                 opSpecArgCount(opSpec("VectorCompare", OpEmitterTable, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(2)),
	OpGetField:                      opSpec("GetField", OpEmitterField, OpArgFixedAux, OpSideEffectRead, true),
	OpGetFieldNumToFloat:            opSpec("GetFieldNumToFloat", OpEmitterField, OpArgFixedAux, OpSideEffectRead, true),
	OpFieldPolyLen:                  opSpecArgCount(opSpec("FieldPolyLen", OpEmitterField, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(1)),
	OpFieldSvals:                    opSpecArgCount(opSpec("FieldSvals", OpEmitterField, OpArgFixed, OpSideEffectRead, true), OpFixedCount(1)),
	OpFieldLoad:                     opSpecArgCount(opSpec("FieldLoad", OpEmitterField, OpArgFixedAux, OpSideEffectRead, false), OpFixedCount(1)),
	OpFieldLoadNumToFloat:           opSpecArgCount(opSpec("FieldLoadNumToFloat", OpEmitterField, OpArgFixedAux, OpSideEffectRead, false), OpFixedCount(1)),
	OpFieldStore:                    opSpecArgCount(opSpec("FieldStore", OpEmitterField, OpArgFixedAux, OpSideEffectWrite, false), OpFixedCount(2)),
	OpSetField:                      opSpec("SetField", OpEmitterField, OpArgFixedAux, OpSideEffectWrite, true),
	OpSetList:                       opSpec("SetList", OpEmitterTable, OpArgVariadic, OpSideEffectWrite, true),
	OpAppend:                        opSpec("Append", OpEmitterTable, OpArgFixed, OpSideEffectWrite, true),
	OpGetGlobal:                     opSpec("GetGlobal", OpEmitterGlobal, OpArgAux, OpSideEffectRead, true),
	OpSetGlobal:                     opSpec("SetGlobal", OpEmitterGlobal, OpArgFixedAux, OpSideEffectWrite, true),
	OpGetUpval:                      opSpec("GetUpval", OpEmitterUpvalue, OpArgAux, OpSideEffectRead, false),
	OpSetUpval:                      opSpec("SetUpval", OpEmitterUpvalue, OpArgFixedAux, OpSideEffectWrite, false),
	OpBoxInt:                        opSpec("BoxInt", OpEmitterConversion, OpArgFixed, OpSideEffectNone, false),
	OpBoxFloat:                      opSpec("BoxFloat", OpEmitterConversion, OpArgFixed, OpSideEffectNone, false),
	OpUnboxInt:                      opSpec("UnboxInt", OpEmitterConversion, OpArgFixed, OpSideEffectNone, true),
	OpUnboxFloat:                    opSpec("UnboxFloat", OpEmitterConversion, OpArgFixed, OpSideEffectNone, true),
	OpNumToFloat:                    opSpec("NumToFloat", OpEmitterConversion, OpArgFixed, OpSideEffectNone, true),
	OpGuardType:                     opSpecArgCount(opSpec("GuardType", OpEmitterGuard, OpArgFixedAux, OpSideEffectNone, true), OpFixedCount(1)),
	OpGuardIntRange:                 opSpec("GuardIntRange", OpEmitterGuard, OpArgFixedAux, OpSideEffectNone, true),
	OpGuardGlobalConst:              opSpecArgCount(opSpec("GuardGlobalConst", OpEmitterGuard, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(0)),
	OpGuardConstString:              opSpecArgCount(opSpec("GuardConstString", OpEmitterGuard, OpArgFixedAux, OpSideEffectNone, true), OpFixedCount(1)),
	OpGuardTableKind:                opSpecArgCount(opSpec("GuardTableKind", OpEmitterGuard, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(1)),
	OpGuardCalleeProto:              opSpecArgCount(opSpec("GuardCalleeProto", OpEmitterGuard, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(1)),
	OpGuardFieldCalleeProto:         opSpecArgCount(opSpec("GuardFieldCalleeProto", OpEmitterGuard, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(1)),
	OpGuardShapeFieldType:           opSpecArgCount(opSpec("GuardShapeFieldType", OpEmitterGuard, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(0)),
	OpGuardShapeFieldTypeMask:       opSpecArgCount(opSpec("GuardShapeFieldTypeMask", OpEmitterGuard, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(0)),
	OpGuardShapeFieldVMClosure:      opSpecArgCount(opSpec("GuardShapeFieldVMClosure", OpEmitterGuard, OpArgFixedAux, OpSideEffectRead, true), OpFixedCount(0)),
	OpGuardNonNil:                   opSpecArgCount(opSpec("GuardNonNil", OpEmitterGuard, OpArgFixed, OpSideEffectNone, true), OpFixedCount(1)),
	OpGuardTruthy:                   opSpecArgCount(opSpec("GuardTruthy", OpEmitterGuard, OpArgFixed, OpSideEffectNone, true), OpFixedCount(1)),
	OpJump:                          opTerminatorSpec("Jump", OpArgControl, OpFixedCount(0), 1),
	OpBranch:                        opTerminatorSpec("Branch", OpArgControl, OpFixedCount(1), 2),
	OpReturn:                        opTerminatorSpec("Return", OpArgVariadic, OpRangedCount(0, OpCountAny), 0),
	OpCall:                          opSpec("Call", OpEmitterCall, OpArgVariadic, OpSideEffectCall, true),
	OpCallFloor:                     opSpec("CallFloor", OpEmitterCall, OpArgVariadic, OpSideEffectCall, true),
	OpFieldCallFloor:                opSpec("FieldCallFloor", OpEmitterCall, OpArgVariadic, OpSideEffectCall, true),
	OpResume:                        opSpec("Resume", OpEmitterCall, OpArgVariadicAux, OpSideEffectCall, true),
	OpYield:                         opSpec("Yield", OpEmitterCall, OpArgVariadicAux, OpSideEffectCall, true),
	OpSelf:                          opSpec("Self", OpEmitterCall, OpArgFixed, OpSideEffectCall, true),
	OpForPrep:                       opSpec("ForPrep", OpEmitterLoop, OpArgFixedAux, OpSideEffectControl, true),
	OpForLoop:                       opSpec("ForLoop", OpEmitterLoop, OpArgFixedAux, OpSideEffectControl, true),
	OpTForCall:                      opSpec("TForCall", OpEmitterLoop, OpArgVariadicAux, OpSideEffectCall, true),
	OpTForLoop:                      opSpec("TForLoop", OpEmitterLoop, OpArgFixedAux, OpSideEffectControl, false),
	OpClosure:                       opSpec("Closure", OpEmitterClosure, OpArgAux, OpSideEffectAllocate, true),
	OpClose:                         opSpec("Close", OpEmitterClosure, OpArgAux, OpSideEffectWrite, true),
	OpVararg:                        opSpec("Vararg", OpEmitterVararg, OpArgAux, OpSideEffectRead, true),
	OpTestSet:                       opSpec("TestSet", OpEmitterControl, OpArgFixedAux, OpSideEffectControl, false),
	OpGo:                            opSpec("Go", OpEmitterConcurrency, OpArgVariadic, OpSideEffectConcurrency, true),
	OpMakeChan:                      opSpec("MakeChan", OpEmitterConcurrency, OpArgAux, OpSideEffectAllocate, true),
	OpSend:                          opSpec("Send", OpEmitterConcurrency, OpArgFixed, OpSideEffectConcurrency, true),
	OpRecv:                          opSpec("Recv", OpEmitterConcurrency, OpArgFixed, OpSideEffectConcurrency, true),
	OpPhi:                           opSpec("Phi", OpEmitterPhi, OpArgVariadic, OpSideEffectNone, false),
	OpNop:                           opSpec("Nop", OpEmitterSpecial, OpArgNone, OpSideEffectNone, false),
}
