print("case:math_tonumber_basic")

assert(tonumber(3.4) == 3.4)
assert(tonumber(3) == 3)
assert(tonumber("0") == 0)
assert(!tonumber(""))
assert(!tonumber("  "))
assert(!tonumber("-"))
assert(!tonumber("  -0x "))
assert(!tonumber({}))
assert(tonumber("+0.01") == 1 / 100)
assert(tonumber("+.01") == 0.01)
assert(tonumber(".01") == 0.01)
assert(tonumber("-1.") == -1)
assert(tonumber("+1.") == 1)
assert(!tonumber("+ 0.01"))
assert(!tonumber("+.e1"))
assert(!tonumber("1e"))
assert(!tonumber("1.0e+"))
assert(!tonumber("."))
assert(tonumber("-1.2e2") == - - -120)

print("ok")
