print("case:regexp_submatch_limits_more")

all := regexp.findAllSubmatch("([a-z]+)([0-9]+)", "a1 bb22 ccc333", 2)
assert(#all == 2)
assert(#all[1] == 3)
assert(all[1][1] == "a1")
assert(all[1][2] == "a")
assert(all[1][3] == "1")
assert(all[2][1] == "bb22")
assert(all[2][2] == "bb")
assert(all[2][3] == "22")

none := regexp.findAllSubmatch("([0-9]+)", "abc")
assert(#none == 0)

optional := regexp.findAllSubmatch("a(b)?", "a ab", -1)
assert(#optional == 2)
assert(optional[1][1] == "a")
assert(optional[1][2] == "")
assert(optional[2][1] == "ab")
assert(optional[2][2] == "b")

limitedFind := regexp.findAll("[0-9]+", "a1b22c333", 2)
assert(#limitedFind == 2)
assert(limitedFind[1] == "1")
assert(limitedFind[2] == "22")

zeroFind := regexp.findAll("[0-9]+", "a1b22", 0)
assert(#zeroFind == 0)

splitTwo := regexp.split(",", "a,b,c,d", 2)
assert(#splitTwo == 2)
assert(splitTwo[1] == "a")
assert(splitTwo[2] == "b,c,d")

splitZero := regexp.split(",", "a,b", 0)
assert(#splitZero == 0)

re := regexp.mustCompile("([a-z]+)([0-9]+)")
compiledAll := re.findAllSubmatch("a1 bb22 ccc333", 2)
assert(#compiledAll == 2)
assert(compiledAll[1][1] == "a1")
assert(compiledAll[1][2] == "a")
assert(compiledAll[1][3] == "1")
assert(compiledAll[2][1] == "bb22")
assert(compiledAll[2][2] == "bb")
assert(compiledAll[2][3] == "22")
assert(re.numSubexp() == 2)

compiledFind := re.findAll("a1 bb22 ccc333", 1)
assert(#compiledFind == 1)
assert(compiledFind[1] == "a1")

compiledSplitRe := regexp.mustCompile(",")
compiledSplit := compiledSplitRe.split("a,b,c,d", 3)
assert(#compiledSplit == 3)
assert(compiledSplit[1] == "a")
assert(compiledSplit[2] == "b")
assert(compiledSplit[3] == "c,d")

compiledZeroSplit := compiledSplitRe.split("a,b", 0)
assert(#compiledZeroSplit == 0)

noCapture := regexp.mustCompile("[0-9]+")
assert(noCapture.numSubexp() == 0)

nested := regexp.mustCompile("(a(b))(c)?")
assert(nested.numSubexp() == 3)
nestedAll := nested.findAllSubmatch("ab abc", -1)
assert(#nestedAll == 2)
assert(nestedAll[1][1] == "ab")
assert(nestedAll[1][2] == "ab")
assert(nestedAll[1][3] == "b")
assert(nestedAll[1][4] == "")
assert(nestedAll[2][1] == "abc")
assert(nestedAll[2][2] == "ab")
assert(nestedAll[2][3] == "b")
assert(nestedAll[2][4] == "c")

print("ok")
