print("case:time_compress_encoding_go_host_more")

t0 := time.unix(1700000000)
assert(t0.year == 2023)
assert(t0.month == 11)
assert(t0.day == 14)
assert(time.format(t0, "%Y-%m-%d %H:%M:%S") == "2023-11-14 22:13:20")

parsed, err := time.parse("2024-01-02 03:04:05", "%Y-%m-%d %H:%M:%S")
assert(err == nil)
assert(parsed.year == 2024)
assert(parsed.month == 1)
assert(parsed.day == 2)
plus := time.add(parsed, time.HOUR)
assert(time.diff(parsed, plus) == 3600)
assert(time.isBefore(parsed, plus))
assert(time.isAfter(plus, parsed))
assert(time.weekday(parsed) == "Tuesday")
assert(time.month(parsed) == "January")
badTime, err := time.parse("bad", "%Y")
assert(badTime == nil)
assert(type(err) == "string")

payload := "hello hello hello"
gz := compress.gzipEncode(payload)
out, err := compress.gzipDecode(gz)
assert(out == payload)
assert(err == nil)
zl := compress.zlibEncode(payload)
out, err = compress.zlibDecode(zl)
assert(out == payload)
assert(err == nil)
df := compress.deflateEncode(payload)
out, err = compress.deflateDecode(df)
assert(out == payload)
assert(err == nil)
out, err = compress.gzipDecode("bad")
assert(out == nil)
assert(type(err) == "string")

assert(encoding.hexEncode("go") == "676f")
txt, err := encoding.hexDecode("676f")
assert(txt == "go")
assert(err == nil)
txt, err = encoding.hexDecode("xx")
assert(txt == nil)
assert(type(err) == "string")
assert(encoding.base32Encode("go") == "M5XQ====")
txt, err = encoding.base32Decode("M5XQ====")
assert(txt == "go")
assert(err == nil)
assert(encoding.base32HexEncode("go") == "CTNG")
txt, err = encoding.base32HexDecode("CTNG")
assert(txt == "go")
assert(err == nil)
ini := encoding.iniDecode("name=gscript\n[server]\nport=8080\n")
assert(ini.name == "gscript")
assert(ini.server.port == "8080")
escaped := encoding.xmlEscape("<x a=\"1\">&</x>")
assert(escaped == "&lt;x a=&#34;1&#34;&gt;&amp;&lt;/x&gt;")
assert(encoding.xmlUnescape("&lt;x&gt;&amp;&lt;/x&gt;") == "<x>&</x>")

print("ok")
