package main

import (
	"flag"
	"fmt"
	"html"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var specPreviewChapters = []struct {
	File  string
	Title string
}{
	{"index.md", "Introduction"},
	{"notation.md", "Notation"},
	{"source.md", "Source code representation"},
	{"lexical.md", "Lexical elements"},
	{"declarations.md", "Declarations and scope"},
	{"values.md", "Values and types"},
	{"expressions.md", "Expressions"},
	{"statements.md", "Statements"},
	{"functions.md", "Functions"},
	{"tables.md", "Tables and metatables"},
	{"concurrency.md", "Concurrency"},
	{"dialects.md", "Tagged Dialects"},
	{"ai-dialect.md", "AI Dialect Syntax"},
	{"modules.md", "Modules and loading"},
	{"errors.md", "Errors and diagnostics"},
	{"implementation.md", "Implementation requirements"},
}

var (
	specPreviewGeneratedStart = "<!-- BEGIN GENERATED SPEC CHAPTERS -->"
	specPreviewGeneratedEnd   = "<!-- END GENERATED SPEC CHAPTERS -->"
	specPreviewKeywords       = wordSet("break chan const continue defer else elseif for func go goto if in range return var")
	specPreviewConstants      = wordSet("false nil true")
	specPreviewBuiltins       = wordSet("assert cap close collectgarbage dofile error getmetatable ipairs len load loadfile loadstring next pairs pcall print rawequal rawget rawlen rawset require select setmetatable spread tonumber tostring type unpack xpcall")
	specPreviewOpRE           = regexp.MustCompile(`\.\.\.|\+\+|--|\+=|-=|\*=|/=|:=|==|!=|<=|>=|&&|\|\||&\^|<<|>>|<-|\.\.|\*\*|[+\-*/%=<>!#&|^]`)
	specPreviewNumberRE       = regexp.MustCompile(`(?i)(?:0x[0-9a-f](?:_?[0-9a-f])*|0b[01](?:_?[01])*|0o[0-7](?:_?[0-7])*|(?:[0-9](?:_?[0-9])*)\.(?:[0-9](?:_?[0-9])*)?(?:e[+-]?[0-9](?:_?[0-9])*)?|(?:[0-9](?:_?[0-9])*)e[+-]?[0-9](?:_?[0-9])*|[0-9](?:_?[0-9])*)`)
	specPreviewIdentRE        = regexp.MustCompile(`[A-Za-z_][A-Za-z0-9_]*`)
	specPreviewOLRE           = regexp.MustCompile(`^\d+\. `)
	specPreviewLinkRE         = regexp.MustCompile(`\[([^\]]+)\]\(([^)]+)\)`)
	specPreviewCodeRE         = regexp.MustCompile("`([^`]+)`")
	specPreviewSlugRE         = regexp.MustCompile(`[^a-z0-9]+`)
)

func runDocSpecPreviewCommand(args []string, outw, errw io.Writer) int {
	root, ok := currentLeiaRepoRoot()
	if !ok {
		if cwd, err := os.Getwd(); err == nil {
			root = cwd
		}
	}
	fs := flag.NewFlagSet("doc spec-preview", flag.ContinueOnError)
	fs.SetOutput(errw)
	specDir := fs.String("spec-dir", filepath.Join(root, "docs", "spec"), "directory containing spec Markdown files")
	output := fs.String("output", filepath.Join(os.TempDir(), "leia-spec-preview.html"), "write generated HTML to a file")
	writeIndex := fs.Bool("write-index", false, "regenerate spec-dir/index.md from the chapter files before rendering")
	if err := fs.Parse(args); err != nil {
		if err == flag.ErrHelp {
			return 0
		}
		return 2
	}
	if len(fs.Args()) != 0 {
		fmt.Fprintln(errw, "usage: leia doc spec-preview [--spec-dir DIR] [--output FILE] [--write-index]")
		return 2
	}
	if *writeIndex {
		indexText, err := buildSpecPreviewIndexMarkdown(*specDir)
		if err != nil {
			fmt.Fprintf(errw, "leia doc spec-preview: %v\n", err)
			return 1
		}
		if err := os.WriteFile(filepath.Join(*specDir, "index.md"), []byte(indexText), 0644); err != nil {
			fmt.Fprintf(errw, "leia doc spec-preview: %v\n", err)
			return 1
		}
	}
	htmlText, err := renderSpecPreview(*specDir)
	if err != nil {
		fmt.Fprintf(errw, "leia doc spec-preview: %v\n", err)
		return 1
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0755); err != nil {
		fmt.Fprintf(errw, "leia doc spec-preview: %v\n", err)
		return 1
	}
	if err := os.WriteFile(*output, []byte(htmlText), 0644); err != nil {
		fmt.Fprintf(errw, "leia doc spec-preview: %v\n", err)
		return 1
	}
	fmt.Fprintln(outw, *output)
	return 0
}

func buildSpecPreviewIndexMarkdown(specDir string) (string, error) {
	indexPath := filepath.Join(specDir, "index.md")
	data, err := os.ReadFile(indexPath)
	if err != nil {
		return "", err
	}
	intro := strings.TrimRight(stripGeneratedSpecChapters(string(data)), "\n")
	var parts []string
	parts = append(parts,
		intro,
		"",
		specPreviewGeneratedStart,
		"<!-- Generated by leia doc spec-preview. Edit the chapter files, then regenerate this index. -->",
		"",
	)
	for _, chapter := range specPreviewChapters {
		if chapter.File == "index.md" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(specDir, chapter.File))
		if err != nil {
			return "", err
		}
		parts = append(parts, normalizeSpecPreviewPublishedFences(shiftSpecPreviewMarkdownHeadings(string(data), 1)), "")
	}
	grammar, err := os.ReadFile(filepath.Join(specDir, "grammar.ebnf"))
	if err != nil {
		return "", err
	}
	parts = append(parts,
		"## Grammar appendix",
		"",
		"```ebnf",
		strings.TrimRight(string(grammar), "\n"),
		"```",
		"",
		specPreviewGeneratedEnd,
		"",
	)
	return strings.Join(parts, "\n"), nil
}

func stripGeneratedSpecChapters(text string) string {
	start := strings.Index(text, specPreviewGeneratedStart)
	if start == -1 {
		return strings.TrimRight(text, "\n") + "\n"
	}
	return strings.TrimRight(text[:start], "\n") + "\n"
}

func shiftSpecPreviewMarkdownHeadings(text string, levels int) string {
	lines := strings.Split(strings.ReplaceAll(text, "\r\n", "\n"), "\n")
	for i, line := range lines {
		count := 0
		for count < len(line) && count < 6 && line[count] == '#' {
			count++
		}
		if count > 0 && count < len(line) && (line[count] == ' ' || line[count] == '\t') {
			newCount := count + levels
			if newCount > 6 {
				newCount = 6
			}
			lines[i] = strings.Repeat("#", newCount) + line[count:]
		}
	}
	return strings.TrimRight(strings.Join(lines, "\n"), "\n") + "\n"
}

func normalizeSpecPreviewPublishedFences(text string) string {
	lines := strings.Split(strings.ReplaceAll(text, "\r\n", "\n"), "\n")
	forms := map[string]bool{
		"```leia run":      true,
		"```leia run all":  true,
		"```leia fail":     true,
		"```leia fail all": true,
	}
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if forms[trimmed] {
			prefixLen := len(line) - len(strings.TrimLeft(line, " \t"))
			lines[i] = line[:prefixLen] + "```leia"
		}
	}
	return strings.TrimRight(strings.Join(lines, "\n"), "\n") + "\n"
}

func renderSpecPreview(specDir string) (string, error) {
	var nav strings.Builder
	var sections strings.Builder
	for _, chapter := range specPreviewChapters {
		data, err := os.ReadFile(filepath.Join(specDir, chapter.File))
		if err != nil {
			return "", err
		}
		ident := specPreviewSlug(chapter.Title)
		fmt.Fprintf(&nav, `<li><a href="#%s">%s</a></li>`, ident, html.EscapeString(chapter.Title))
		sections.WriteString("<section>")
		chapterText := string(data)
		if chapter.File == "index.md" {
			chapterText = stripGeneratedSpecChapters(chapterText)
		}
		sections.WriteString(specPreviewMarkdownToHTML(chapterText, ident))
		sections.WriteString("</section>")
	}
	grammar, err := os.ReadFile(filepath.Join(specDir, "grammar.ebnf"))
	if err != nil {
		return "", err
	}
	nav.WriteString(`<li><a href="#grammar-appendix">Grammar appendix</a></li>`)
	sections.WriteString(`<section><h2 id="grammar-appendix">Grammar appendix</h2><pre class="language-ebnf"><code class="language-ebnf">`)
	sections.WriteString(html.EscapeString(string(grammar)))
	sections.WriteString("</code></pre></section>")

	out := strings.ReplaceAll(specPreviewHTMLTemplate, "{nav}", nav.String())
	out = strings.ReplaceAll(out, "{sections}", sections.String())
	out = strings.ReplaceAll(out, "{spec_dir}", html.EscapeString(specDir))
	return out, nil
}

func specPreviewMarkdownToHTML(text, prefix string) string {
	lines := specPreviewMarkdownLines(text)
	var out []string
	var paragraph []string
	var code []string
	inCode := false
	codeInfo := ""
	inUL := false
	inOL := false
	ids := make(map[string]int)
	uniqueID := func(base string) string {
		ids[base]++
		if ids[base] == 1 {
			return base
		}
		return fmt.Sprintf("%s-%d", base, ids[base])
	}

	closeParagraph := func() {
		if len(paragraph) > 0 {
			out = append(out, "<p>"+specPreviewInlineMarkdown(strings.Join(paragraph, " "))+"</p>")
			paragraph = nil
		}
	}
	closeLists := func() {
		if inUL {
			out = append(out, "</ul>")
			inUL = false
		}
		if inOL {
			out = append(out, "</ol>")
			inOL = false
		}
	}

	for i := 0; i < len(lines); {
		line := lines[i]
		if strings.HasPrefix(line, "```") {
			closeParagraph()
			closeLists()
			if inCode {
				out = append(out, specPreviewRenderCodeBlock(strings.Join(code, "\n"), codeInfo))
				code = nil
				codeInfo = ""
				inCode = false
			} else {
				inCode = true
				codeInfo = strings.TrimSpace(line[3:])
			}
			i++
			continue
		}
		if inCode {
			code = append(code, line)
			i++
			continue
		}
		trimmedLine := strings.TrimSpace(line)
		if strings.HasPrefix(trimmedLine, "<!--") && strings.HasSuffix(trimmedLine, "-->") {
			i++
			continue
		}
		if strings.HasPrefix(strings.TrimSpace(line), "|") && i+1 < len(lines) && specPreviewIsTableSeparator(lines[i+1]) {
			closeParagraph()
			closeLists()
			header := specPreviewSplitTableRow(line)
			i += 2
			var rows [][]string
			for i < len(lines) && strings.HasPrefix(strings.TrimSpace(lines[i]), "|") {
				rows = append(rows, specPreviewSplitTableRow(lines[i]))
				i++
			}
			out = append(out, `<div class="table-wrap"><table>`)
			var h strings.Builder
			h.WriteString("<thead><tr>")
			for _, cell := range header {
				h.WriteString("<th>" + specPreviewInlineMarkdown(cell) + "</th>")
			}
			h.WriteString("</tr></thead>")
			out = append(out, h.String(), "<tbody>")
			for _, row := range rows {
				var r strings.Builder
				r.WriteString("<tr>")
				for col := 0; col < len(header); col++ {
					cell := ""
					if col < len(row) {
						cell = row[col]
					}
					r.WriteString("<td>" + specPreviewInlineMarkdown(cell) + "</td>")
				}
				r.WriteString("</tr>")
				out = append(out, r.String())
			}
			out = append(out, "</tbody></table></div>")
			continue
		}
		if strings.TrimSpace(line) == "" {
			closeParagraph()
			closeLists()
			i++
			continue
		}
		switch {
		case strings.HasPrefix(line, "# "):
			closeParagraph()
			closeLists()
			out = append(out, fmt.Sprintf(`<h2 id="%s">%s</h2>`, uniqueID(prefix), html.EscapeString(strings.TrimSpace(line[2:]))))
		case strings.HasPrefix(line, "## "):
			closeParagraph()
			closeLists()
			title := strings.TrimSpace(line[3:])
			out = append(out, fmt.Sprintf(`<h3 id="%s">%s</h3>`, uniqueID(prefix+"-"+specPreviewSlug(title)), html.EscapeString(title)))
		case strings.HasPrefix(line, "### "):
			closeParagraph()
			closeLists()
			title := strings.TrimSpace(line[4:])
			out = append(out, fmt.Sprintf(`<h4 id="%s">%s</h4>`, uniqueID(prefix+"-"+specPreviewSlug(title)), html.EscapeString(title)))
		case strings.HasPrefix(line, "- "):
			closeParagraph()
			if !inUL {
				closeLists()
				out = append(out, "<ul>")
				inUL = true
			}
			out = append(out, "<li>"+specPreviewInlineMarkdown(strings.TrimSpace(line[2:]))+"</li>")
		case specPreviewOLRE.MatchString(line):
			closeParagraph()
			if !inOL {
				closeLists()
				out = append(out, "<ol>")
				inOL = true
			}
			item := specPreviewOLRE.ReplaceAllString(line, "")
			out = append(out, "<li>"+specPreviewInlineMarkdown(strings.TrimSpace(item))+"</li>")
		case (inUL || inOL) && (strings.HasPrefix(line, "  ") || strings.HasPrefix(line, "\t")) && len(out) > 0 && strings.HasSuffix(out[len(out)-1], "</li>"):
			last := out[len(out)-1]
			out[len(out)-1] = strings.TrimSuffix(last, "</li>") + " " + specPreviewInlineMarkdown(strings.TrimSpace(line)) + "</li>"
		default:
			closeLists()
			paragraph = append(paragraph, strings.TrimSpace(line))
		}
		i++
	}
	closeParagraph()
	closeLists()
	if inCode {
		out = append(out, specPreviewRenderCodeBlock(strings.Join(code, "\n"), codeInfo))
	}
	return strings.Join(out, "\n")
}

func specPreviewMarkdownLines(text string) []string {
	lines := strings.Split(strings.ReplaceAll(text, "\r\n", "\n"), "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "---" {
		return lines
	}
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "---" {
			return lines[i+1:]
		}
	}
	return lines
}

func specPreviewInlineMarkdown(text string) string {
	escaped := html.EscapeString(text)
	escaped = specPreviewCodeRE.ReplaceAllString(escaped, "<code>$1</code>")
	escaped = specPreviewLinkRE.ReplaceAllStringFunc(escaped, func(match string) string {
		parts := specPreviewLinkRE.FindStringSubmatch(match)
		if len(parts) != 3 {
			return match
		}
		return `<a href="` + html.EscapeString(specPreviewPreviewHref(parts[2])) + `">` + parts[1] + `</a>`
	})
	return escaped
}

func specPreviewPreviewHref(target string) string {
	target = strings.TrimSpace(target)
	target = strings.Trim(target, `"'`)
	if target == "" || target == "#" {
		return "#"
	}
	if strings.HasPrefix(target, "#") || strings.Contains(target, "://") || strings.HasPrefix(target, "mailto:") {
		return target
	}
	base := target
	fragment := ""
	if idx := strings.IndexByte(base, '#'); idx >= 0 {
		fragment = base[idx+1:]
		base = base[:idx]
	}
	if base == "grammar.ebnf" {
		if fragment != "" {
			return "#grammar-appendix-" + specPreviewSlug(fragment)
		}
		return "#grammar-appendix"
	}
	for _, chapter := range specPreviewChapters {
		if base == chapter.File {
			href := "#" + specPreviewSlug(chapter.Title)
			if fragment != "" {
				href += "-" + specPreviewSlug(fragment)
			}
			return href
		}
	}
	return target
}

func specPreviewRenderCodeBlock(source, info string) string {
	fields := strings.Fields(info)
	language := ""
	if len(fields) > 0 {
		language = fields[0]
	}
	if language == "leia" {
		classes := "language-leia leia-code"
		return `<pre class="` + classes + `"><code class="` + classes + `">` + specPreviewHighlightLeia(source) + "</code></pre>"
	}
	if language != "" {
		classAttr := ` class="language-` + html.EscapeString(language) + `"`
		return "<pre" + classAttr + "><code" + classAttr + ">" + html.EscapeString(source) + "</code></pre>"
	}
	return "<pre><code>" + html.EscapeString(source) + "</code></pre>"
}

func specPreviewHighlightLeia(source string) string {
	var out strings.Builder
	for i := 0; i < len(source); {
		text := source[i:]
		if strings.HasPrefix(text, "/*") {
			end := strings.Index(source[i+2:], "*/")
			if end == -1 {
				end = len(source)
			} else {
				end = i + 2 + end + 2
			}
			out.WriteString(specPreviewSpan("tok-comment", source[i:end]))
			i = end
			continue
		}
		if strings.HasPrefix(text, "//") {
			end := strings.IndexByte(source[i:], '\n')
			if end == -1 {
				end = len(source)
			} else {
				end = i + end
			}
			comment := source[i:end]
			className := "tok-comment"
			if strings.HasPrefix(comment, "//leia:") {
				className = "tok-directive"
			}
			out.WriteString(specPreviewSpan(className, comment))
			i = end
			continue
		}
		if source[i] == '"' || source[i] == '\'' {
			quote := source[i]
			j := i + 1
			escaped := false
			for j < len(source) {
				current := source[j]
				if escaped {
					escaped = false
				} else if current == '\\' {
					escaped = true
				} else if current == quote {
					j++
					break
				}
				j++
			}
			out.WriteString(specPreviewSpan("tok-string", source[i:j]))
			i = j
			continue
		}
		if source[i] == '`' {
			j := strings.IndexByte(source[i+1:], '`')
			if j == -1 {
				j = len(source)
			} else {
				j = i + 1 + j + 1
			}
			out.WriteString(specPreviewSpan("tok-string", source[i:j]))
			i = j
			continue
		}
		if loc := specPreviewNumberRE.FindStringIndex(source[i:]); loc != nil && loc[0] == 0 {
			token := source[i : i+loc[1]]
			out.WriteString(specPreviewSpan("tok-number", token))
			i += loc[1]
			continue
		}
		if loc := specPreviewIdentRE.FindStringIndex(source[i:]); loc != nil && loc[0] == 0 {
			token := source[i : i+loc[1]]
			switch {
			case specPreviewKeywords[token]:
				out.WriteString(specPreviewSpan("tok-keyword", token))
			case specPreviewConstants[token]:
				out.WriteString(specPreviewSpan("tok-constant", token))
			case specPreviewBuiltins[token]:
				out.WriteString(specPreviewSpan("tok-builtin", token))
			default:
				out.WriteString(html.EscapeString(token))
			}
			i += loc[1]
			continue
		}
		if loc := specPreviewOpRE.FindStringIndex(source[i:]); loc != nil && loc[0] == 0 {
			token := source[i : i+loc[1]]
			out.WriteString(specPreviewSpan("tok-operator", token))
			i += loc[1]
			continue
		}
		out.WriteString(html.EscapeString(source[i : i+1]))
		i++
	}
	return out.String()
}

func specPreviewSpan(className, text string) string {
	return `<span class="` + className + `">` + html.EscapeString(text) + "</span>"
}

func specPreviewSlug(text string) string {
	return strings.Trim(specPreviewSlugRE.ReplaceAllString(strings.ToLower(text), "-"), "-")
}

func specPreviewIsTableSeparator(line string) bool {
	cells := specPreviewSplitTableRow(line)
	if len(cells) == 0 {
		return false
	}
	for _, cell := range cells {
		cell = strings.TrimSpace(cell)
		if len(cell) < 3 {
			return false
		}
		for i, r := range cell {
			if r == '-' {
				continue
			}
			if (i == 0 || i == len(cell)-1) && r == ':' {
				continue
			}
			return false
		}
	}
	return true
}

func specPreviewSplitTableRow(line string) []string {
	text := strings.TrimSpace(line)
	text = strings.TrimPrefix(text, "|")
	text = strings.TrimSuffix(text, "|")
	var cells []string
	var current strings.Builder
	inCode := false
	escaped := false
	for _, r := range text {
		if escaped {
			current.WriteRune(r)
			escaped = false
			continue
		}
		if r == '\\' {
			current.WriteRune(r)
			escaped = true
			continue
		}
		if r == '`' {
			current.WriteRune(r)
			inCode = !inCode
			continue
		}
		if r == '|' && !inCode {
			cells = append(cells, strings.TrimSpace(current.String()))
			current.Reset()
			continue
		}
		current.WriteRune(r)
	}
	cells = append(cells, strings.TrimSpace(current.String()))
	return cells
}

func wordSet(words string) map[string]bool {
	out := map[string]bool{}
	for _, word := range strings.Fields(words) {
		out[word] = true
	}
	return out
}

const specPreviewHTMLTemplate = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Leia Language Specification</title>
<style>
:root {
  --blue:#007d9c;
  --blue-dark:#005f73;
  --ink:#202224;
  --muted:#5f6368;
  --line:#dadce0;
  --code-bg:#f6f8fa;
}
html { scroll-behavior:smooth; }
body {
  margin:0;
  color:var(--ink);
  background:white;
  font-family:Arial, Helvetica, sans-serif;
  font-size:16px;
  line-height:1.55;
}
a { color:var(--blue-dark); text-decoration:none; }
a:hover { text-decoration:underline; }
.topbar {
  height:56px;
  display:flex;
  align-items:center;
  gap:18px;
  padding:0 24px;
  border-bottom:1px solid var(--line);
  background:#fff;
  position:sticky;
  top:0;
  z-index:3;
}
.brand { font-size:22px; font-weight:700; color:var(--blue); letter-spacing:.2px; }
.topbar span:last-child { color:var(--muted); font-size:14px; }
.shell {
  display:grid;
  grid-template-columns:260px minmax(0, 920px);
  gap:42px;
  max-width:1280px;
  margin:0 auto;
  padding:28px 32px 72px;
}
nav {
  position:sticky;
  top:76px;
  align-self:start;
  max-height:calc(100vh - 96px);
  overflow:auto;
  border-right:1px solid var(--line);
  padding-right:20px;
}
.toc-details > summary {
  display:none;
}
nav h2 {
  font-size:13px;
  text-transform:uppercase;
  letter-spacing:.08em;
  color:var(--muted);
  margin:0 0 10px;
}
nav ol { list-style:none; margin:0; padding:0; }
nav a { display:block; padding:5px 0; font-size:14px; color:#394247; }
main { min-width:0; }
main > header { margin-bottom:28px; border-bottom:1px solid var(--line); padding-bottom:22px; }
h1 { font-size:34px; line-height:1.16; margin:0 0 10px; font-weight:500; }
.subtitle { color:var(--muted); max-width:760px; margin:0; }
section { margin:0 0 34px; }
h2 {
  font-size:28px;
  line-height:1.2;
  font-weight:500;
  margin:38px 0 14px;
  padding-top:18px;
  border-top:1px solid var(--line);
}
section:first-of-type h2 { border-top:0; padding-top:0; margin-top:0; }
h3 { font-size:21px; line-height:1.25; font-weight:500; margin:28px 0 10px; }
h4 { font-size:17px; line-height:1.3; font-weight:700; margin:22px 0 8px; }
p { margin:10px 0; max-width:820px; }
ul, ol { max-width:820px; padding-left:28px; }
li { margin:5px 0; }
code { font-family:Menlo, Consolas, 'Liberation Mono', monospace; font-size:.92em; }
p code, li code { background:var(--code-bg); border:1px solid #e5e7eb; border-radius:3px; padding:1px 4px; }
pre { background:var(--code-bg); border:1px solid var(--line); border-radius:4px; overflow:auto; padding:14px 16px; max-width:920px; }
pre code { background:transparent; border:0; padding:0; color:#111827; }
pre.leia-code {
  background:#f8fbfd;
  border-color:#cfe3ea;
}
.tok-comment { color:#6a737d; font-style:italic; }
.tok-directive { color:#0f766e; font-weight:600; }
.tok-string { color:#0b7285; }
.tok-number { color:#8a4baf; }
.tok-keyword { color:#005f73; font-weight:600; }
.tok-contextual { color:#7c3aed; font-weight:600; }
.tok-constant { color:#9a3412; font-weight:600; }
.tok-builtin { color:#0369a1; }
.tok-operator { color:#6b21a8; }
.table-wrap { max-width:920px; overflow-x:auto; margin:14px 0 18px; }
table { width:100%; border-collapse:collapse; border-top:1px solid var(--line); border-bottom:1px solid var(--line); font-size:14px; }
th, td { text-align:left; vertical-align:top; padding:8px 10px; border-bottom:1px solid #e5e7eb; }
th { font-weight:600; background:#f8fafc; color:#1f2937; white-space:nowrap; }
td { min-width:120px; }
td:first-child, th:first-child { white-space:nowrap; }
tr:last-child td { border-bottom:0; }
footer { color:var(--muted); border-top:1px solid var(--line); margin-top:42px; padding-top:18px; font-size:14px; }
@media (max-width:900px) {
  .shell { display:block; padding:20px; }
  nav { position:static; max-height:none; border-right:0; border-bottom:1px solid var(--line); padding:0 0 18px; margin-bottom:24px; }
  .toc-details > summary {
    display:list-item;
    cursor:pointer;
    color:var(--blue-dark);
    font-size:14px;
    font-weight:600;
    padding:8px 0;
  }
  .toc-details[open] > summary { margin-bottom:6px; }
  nav h2 { position:absolute; width:1px; height:1px; padding:0; margin:-1px; overflow:hidden; clip:rect(0, 0, 0, 0); white-space:nowrap; border:0; }
  nav ol { columns:2; }
  .topbar { padding:0 18px; }
}
@media (max-width:560px) { nav ol { columns:1; } h1 { font-size:28px; } h2 { font-size:24px; } }
</style>
</head>
<body>
<div class="topbar"><span class="brand">Leia</span><span>Language Specification</span></div>
<div class="shell">
<nav aria-label="Table of contents"><details class="toc-details" open><summary>Contents</summary><h2>Contents</h2><ol>{nav}</ol></details></nav>
<main>
<header>
<h1>The Leia Programming Language Specification</h1>
<p class="subtitle">A Go-spec-inspired preview generated from <code>docs/spec/</code>. Markdown remains the source of truth.</p>
</header>
{sections}
<footer>Generated locally from the current worktree: <code>docs/spec/</code>.</footer>
</main>
</div>
<script>
(function () {
  var details = document.querySelector(".toc-details");
  var mobile = window.matchMedia("(max-width: 900px)");
  if (details && mobile.matches) details.removeAttribute("open");
})();
</script>
</body>
</html>
`
